module.exports = {
  mode: "jit",
  purge: {
    // Learn more on https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
    enabled: process.env.NODE_ENV === "production",
    content: [
      "./public/index.html",
      "./src/**/*.html",
      "./src/**/*.vue",
      "./src/styles/**/*.css",
    ],
  },
  darkMode: "class", // or 'media' or 'class'
  prefix: "tw-",
  theme: {
    fontFamily: {
      CircularStd: ["Circular Std", "system-ui"],
      "CircularStd-medium": ["Circular Std Medium", "system-ui"],
      "CircularStd-bold": ["Circular Std Bold", "system-ui"],
      "CircularStd-normal": ["Circular Std Normal", "system-ui"],
    },
    extend: {
      colors: {
        transparent: "transparent",
        primary: { DEFAULT: "#4D84FF", white: "#ffffff" },
        secondary: { DEFAULT: "#001140", dark: "#001E70", light: "#06206B" },
        error: { DEFAULT: "#EB5757", light: "#F5D5CB" },
        success: { DEFAULT: "#27AE60", light: "#D7ECD9", lightest: "#E2F8EB" },
        warning: { DEFAULT: "#E2B93B" },
        lemon: { DEFAULT: "#EBFFF4" },
        info: { DEFAULT: "#2F80ED", light: "#B3E0FF" },
        orange: { DEFAULT: "#C06C00", dark: "#694521", lightest: "#FFF5EA" },
        pastel3: { DEFAULT: "#E5EDFF" },
        gray: {
          DEFAULT: "#8791A7",
          disabled: "#A3A8B3",
          dark: "#E1E6F0",
          darkest: "#D0D5E0",
          light: "#F0F4FD",
          light2: "#FAFBFF",
          lightest: "#F7F9FD",
          lightest1: "#E9EFFF",
          lightest2: "#949DBC",
          lightest3: "#323E67",
          black: "#020B27",
          black2: "#222735",
          bg1: "#4F5877",
          bg2: "#1A2139",
          bg3: "#F6F6EB",
          bg4: "#EFEFEF",
          bg5: "#FCFCFC",
          bg6: "#F1F3F6",
        },
        blue: {
          light: "#85d7ff",
          DEFAULT: "#1fb6ff",
          dark: "#009eeb",
          lightest: "#AFCEE9",
          lightest1: "#FAFBFF",
          lightest2: "##F4F8FF",
          pastel: "#D8EFFF",
          pastel2: "#C8E8FF",
          pastel3: "#E5EDFF",
          bg1: "#6695FF",
          bg2: "#80A7FF",
          bg3: "#C2D3FF",
          bg200: "#E6EDFF",
          ultramarine: "#2A62F5",
          text1: "#2A62F5",
        },
        green: { DEFAULT: "1FAD64" },
        red: {
          error: "#DB4343",
          "error-pink": "#FCE9E9",
        },
        pink: {
          light: "#ff7ce5",
          DEFAULT: "#ff49db",
          dark: "#ff16d1",
        },
        black: {
          dark: "#1A2139",
          DEFAULT: "#020B27",
          light: "#4F5877",
          lightest: "#ffffff",
        },
        purple: {
          light: "#4C5B90",
        },
      },
      outline: {
        primary: "1px solid #4D84FF",
      },
      zIndex: {
        "-10": "-10",
      },
    },
    screens: {
      xxxs: "320px",
      xxs: "375px",
      xs: "425px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xxl: "1440px",
      xxxl: "1536px",
      xxxxl: "1900px",
    },
  },
  variants: {
    extend: {
      opacity: ["disabled"],
      cursor: ["disabled"],
      text: ["disabled"],
      display: ["group-hover"],
    },
  },
  plugins: [],
};
